# Generated by Django 6.0.3 on 2026-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, help_text='Kompyuterdan MP4 video yuklash', null=True, upload_to='videos/courses/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Kompyuterdan MP4 video yuklash', null=True, upload_to='videos/lessons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Tashqi havola (YouTube / Vimeo)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Tashqi havola', max_length=500, null=True),
        ),
    ]
