# Generated by Django 6.0.3 on 2026-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to the video (e.g., YouTube, AWS S3)', max_length=500, null=True),
        ),
    ]
