# Generated by Django 6.0.3 on 2026-03-29 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('courses_enrolled', models.PositiveIntegerField(default=0, help_text='Number of courses the user is currently learning')),
                ('courses_completed', models.PositiveIntegerField(default=0, help_text='Number of courses fully finished')),
                ('total_learning_hours', models.FloatField(default=0.0, help_text='Total hours spent watching videos')),
                ('average_quiz_score', models.FloatField(default=0.0, help_text='Percentage average on quizzes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
